services:
  app:
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    environment:
      TZ: "Asia/Shanghai"
    ports:
      - "20080:80"
      - "20081:81"
      - "20443:443"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
