---
# RKE2 全局配置 (Debian)

# RKE2 版本
rke2_version: v1.28.5+rke2r1
rke2_channel: stable

# 集群配置
cluster_cidr: "10.42.0.0/16"
service_cidr: "10.43.0.0/16"
cluster_dns: "10.43.0.10"
rke2_cni: cilium

# 集群认证 (请修改!)
rke2_token: "f9312967878363961b218bcff7bf4216f8999e5a5a818fdf4e662b9518d7cc9e"
rke2_api_server: "https://192.168.23.132:9345"

# 系统配置
timezone: Asia/Shanghai
system_max_open_files: 655360
system_max_processes: 655360

# 目录配置
rke2_config_dir: /etc/rancher/rke2
rke2_data_dir: /var/lib/rancher/rke2
