apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-config
  namespace: gitea
data:
  app.ini: |
    APP_NAME = Gitea: Git with a cup of tea
    RUN_MODE = prod
    RUN_USER = git

    [server]
    PROTOCOL         = http
    # ⚠️ 重要：部署后需要修改为实际访问地址
    DOMAIN           = 192.168.23.135
    ROOT_URL         = http://192.168.23.135:30300/
    HTTP_PORT        = 3000
    DISABLE_SSH      = false
    SSH_PORT         = 22
    SSH_DOMAIN       = 192.168.23.135
    SSH_LISTEN_PORT  = 22
    START_SSH_SERVER = true
    LFS_START_SERVER = true

    [database]
    DB_TYPE  = sqlite3
    PATH     = /data/gitea/gitea.db
    LOG_SQL  = false

    [repository]
    ROOT = /data/git/repositories

    [security]
    INSTALL_LOCK   = false
    SECRET_KEY     = 
    INTERNAL_TOKEN = 

    [service]
    DISABLE_REGISTRATION              = false
    REQUIRE_SIGNIN_VIEW               = false
    REGISTER_EMAIL_CONFIRM            = false
    ENABLE_NOTIFY_MAIL                = false
    ALLOW_ONLY_EXTERNAL_REGISTRATION  = false
    ENABLE_CAPTCHA                    = false
    DEFAULT_KEEP_EMAIL_PRIVATE        = false
    DEFAULT_ALLOW_CREATE_ORGANIZATION = true
    DEFAULT_ENABLE_TIMETRACKING       = true
    NO_REPLY_ADDRESS                  = noreply.192.168.23.135

    [mailer]
    ENABLED = false

    [session]
    PROVIDER = file

    [log]
    MODE      = console
    LEVEL     = info
    ROOT_PATH = /data/gitea/log

    [webhook]
    ALLOWED_HOST_LIST = *

    [other]
    SHOW_FOOTER_VERSION = true
