apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-config
  namespace: gitea
data:
  # Gitea 配置文件 app.ini
  # 完整配置参考: https://docs.gitea.io/en-us/config-cheat-sheet/
  app.ini: |
    APP_NAME = Gitea: Git with a cup of tea
    RUN_MODE = prod
    RUN_USER = git

    [server]
    PROTOCOL         = http
    DOMAIN           = localhost
    ROOT_URL         = http://localhost:30300/
    HTTP_PORT        = 3000
    DISABLE_SSH      = false
    SSH_PORT         = 22
    START_SSH_SERVER = true
    LFS_START_SERVER = true

    [database]
    DB_TYPE  = sqlite3
    PATH     = /data/gitea/gitea.db
    LOG_SQL  = false

    [repository]
    ROOT = /data/git/repositories

    [security]
    INSTALL_LOCK   = false
    SECRET_KEY     = 
    INTERNAL_TOKEN = 

    [service]
    DISABLE_REGISTRATION              = false
    REQUIRE_SIGNIN_VIEW               = false
    REGISTER_EMAIL_CONFIRM            = false
    ENABLE_NOTIFY_MAIL                = false
    ALLOW_ONLY_EXTERNAL_REGISTRATION  = false
    ENABLE_CAPTCHA                    = false
    DEFAULT_KEEP_EMAIL_PRIVATE        = false
    DEFAULT_ALLOW_CREATE_ORGANIZATION = true
    DEFAULT_ENABLE_TIMETRACKING       = true
    NO_REPLY_ADDRESS                  = noreply.localhost

    [mailer]
    ENABLED = false

    [session]
    PROVIDER = file

    [log]
    MODE      = console
    LEVEL     = info
    ROOT_PATH = /data/gitea/log

    [other]
    SHOW_FOOTER_VERSION = true
