apiVersion: v1
kind: ConfigMap
metadata:
  name: drone-config
  namespace: drone
data:
  # Drone Server 地址（必须配置）
  DRONE_SERVER_HOST: "192.168.23.135:30080"
  DRONE_SERVER_PROTO: "http"
  
  # RPC 协议
  DRONE_RPC_PROTO: "http"
  DRONE_RPC_HOST: "drone-server.drone.svc.cluster.local"
  
  # Git 服务配置（Gitea）
  DRONE_GITEA_SERVER: "http://192.168.23.135:30300"
  
  # 日志级别
  DRONE_LOGS_DEBUG: "true"
  DRONE_LOGS_TRACE: "false"
