apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: drone

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - rbac.yaml
  - drone-server-deployment.yaml
  - drone-server-service.yaml
  - drone-runner-deployment.yaml

# 通用标签
commonLabels:
  app.kubernetes.io/name: drone
  app.kubernetes.io/managed-by: kustomize
