apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo

resources:
  - ../../base

# 生产环境特定补丁
patchesStrategicMerge:
  - replica-patch.yaml

# 添加生产环境标签
commonLabels:
  environment: production
